### ISSUE TITLE
USA TV GO

### ISSUE THREAD

**Issue by JayDigg** [Tempest0580/Temptv#1]
Not getting any thumbnails on networks in USA tv go section? Started a few days ago. Liked to have a widget to this section on my skin, but doesnt look good when theres no icons, lol. Thanks!

**Comment by jewbmx** [comment]
Im almost done fixing this issue and it will most likely get pushed as a update soon for ya.

**Comment by JayDigg** [comment]
Your awesome!! Yea, its weird because the pngs for the icons do resolve if put into a browser like  http://ustvgo.tv/wp-content/uploads/2019/01/bravo-269x151.png. But dont show up in the addon.

**Comment by jewbmx** [comment]
Most likely put a little strain on their site so they did a little update lol. I just ditched their artwork and used wiki and the white studio images repo on my git to fix em up lol. Looks alright and works fine but might change it again to the colored version.

**Comment by JayDigg** [comment]
Sweet, anythings better than nothing.

**Comment by Tempest0580** [comment]
Pushed a update for this.
