### ISSUE TITLE
Last update broke UsaTVGO

### ISSUE THREAD

**Issue by JayDigg** [Tempest0580/Temptv#10]
Ya broke it! LOL

**Comment by JayDigg** [comment]
Reverting to 2.0.15 fixes it.

**Comment by bjgood** [comment]
Yesterday USTVGo was using cloudflare to screen users wanting to visit their site. Today, so far, they've discontinued using cloudflare. They could add it back at any time. Tempest's recent update was to deal with cloudflare at USTVGo.

But, you're right , 2.0.15 does work.

**Comment by Tempest0580** [comment]
Ok I'll look into it. But it seems to be working fine on my end.

**Comment by Tempest0580** [comment]
Is this still broken for you? It works fine for me with the latest update.

**Comment by Tempest0580** [comment]
I'll push a update to fix this after work.

**Comment by Tempest0580** [comment]
Pushed a update with a fix.

**Comment by JayDigg** [comment]
2.0.20. USTVGO still not working here.

**Comment by Tempest0580** [comment]
Ya they changed something on there site this morning already have a fix but cant push it until this afternoon.

**Comment by JayDigg** [comment]
Cool, thanks!

**Comment by Tempest0580** [comment]
Pushed a update to fix this.

**Comment by JayDigg** [comment]
Thanks! Its all good.

**Comment by JayDigg** [comment]
Not Working again..

**Comment by Tempest0580** [comment]
Pushed another update to fix it. Not sure if they are changing the site because of us or to improve the site. Just have to wait and see
