### ISSUE TITLE
ustogo

### ISSUE THREAD

**Issue by gadamou** [Tempest0580/Temptv#11]
ustogo tv no workingg

**Comment by Tempest0580** [comment]
I'll push a update it fix it after work

**Comment by gadamou** [comment]
Thank you
It working fine now.

**Comment by gadamou** [comment]
Today stop working again

**Comment by jewbmx** [comment]
You can close this again if ya want. The issues already resolved again, just gotta wait for the fix to get uploaded

**Comment by Tempest0580** [comment]
The fix will be pushed this afternoon.  Thanks

**Comment by gadamou** [comment]
Thank you very much

**Comment by gadamou** [comment]
Thank you very much
