### ISSUE TITLE
USTVGo down

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/Temptv#12]
Hey Tempest,
Just passing along that USTVGo is down again. They must be on to you and Jewbmx. As soon as you all fix it, they make some changes. 

I can't even right click on their web page and view page source anymore.

**Comment by Tempest0580** [comment]
Pushed a quick fix for this.

**Comment by bjgood** [comment]
Thanks, Tempest.

Have a good one.

Later...

**Comment by Tempest0580** [comment]
Not sure if this is going to break again. They keep doing changes on the site. Could be cause of us or changing the site to improve it. Just have to wait and see

**Comment by JayDigg** [comment]
Gotcha, good luck..

**Comment by YKL66** [comment]
None of these updates after 2015 work for ustvgo for me. I have 4 boxes including win10. Went back to 2015 and it work flawless on all 4 including win10. Not sure why. Just thought I should let you know. Thanks for this addon.

**Comment by Tempest0580** [comment]
Not sure why this is happening. Looks like the only difference now is there is headers added. for me on all my devices the headers make the channels load faster. but ill do more testing

**Comment by bjgood** [comment]
Hey Tempest,
2.0.22 is working fine for me. Just tried it.

Thanks for your efforts, bud.

> Not sure if this is going to break again. They keep doing changes on the site. Could be cause of us or changing the site to improve it. Just have to wait and see

For the longest time USTVGo never put up any protection for their links. But now...wow, it's insane. I can't do anything in bash to scrape their site.

Later...

**Comment by YKL66** [comment]
Thanks for all the hard-work, 2.0.22 is working for me. Just tested the update today from 2.0.15.
