### ISSUE TITLE
FXX

### ISSUE THREAD

**Issue by RickFromTexas** [Tempest0580/Temptv#14]
Just wanted to let the developer know that FXX stopped playing recently. I use Krypton 17.6, TempTV version 2.0.25. If you need to contact me, rfague@outlook.com. Thanks, great addon.

**Comment by Tempest0580** [comment]
Thanks I'll see if I can find another source.

**Comment by Tempest0580** [comment]
Fixed Fxx in UstvGo and a few other channels

**Comment by RickFromTexas** [comment]
Thank you very much! Have a good 1, your hard work is appreciated.
________________________________

**Comment by Tempest0580** [comment]
Your welcome.
