### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by SoulTV** [Tempest0580/Temptv#16]
I'm using this and The Crew live section but I feel like you are using the same sources plus some. I'm just wondering if Fluxus, Lodge and Stratus are a part of TempTV?

**Comment by Tempest0580** [comment]
No I dont use any of them sources.  
If I am its straight from the source and not through them.

**Comment by SoulTV** [comment]
Ah ok, thx. Great addon btw

**Comment by Tempest0580** [comment]
Thanks it's still a work in progress.

**Comment by jewbmx** [comment]
The sources your talking about are located in my 1menu.xml but dont think they are used in TempTV. If they are its probably a couple loose links from em.  If i recall you didnt add em in due to their low quality.
