### ISSUE TITLE
USTV GO Down.

### ISSUE THREAD

**Issue by JayDee696969** [Tempest0580/Temptv#17]
Looks like its down again. Just a heads up..

**Comment by bjgood** [comment]
Yes, it's down for me, too. And, in tempest, as well.

I checked the website, and it's up.

**Comment by Tempest0580** [comment]
I'm aware of it. They changed something on the server. I'm Working on trying to fix it.
Thanks

**Comment by dorrance** [comment]
@Tempest0580 not seeing any code changes seems like it was fixed?

**Comment by Tempest0580** [comment]
Idk yet. I'm working on it,

**Comment by jewbmx** [comment]
They changed up their files or something to that extent, the indexer pulls all the proper links and info used then kodi fails on the play. Take the url and paste it into something like resolveurl tester or try any other play trick and it will always fail in kodi now.  Sample url incase yall cant find one is http://live.savitar.tv/DisneyJr/myStream/playlist.m3u8

**Comment by jewbmx** [comment]
Nevermind i just got it fixed. Had to tinker some more lol   https://textuploader.com/1oudx/raw

**Comment by Tempest0580** [comment]
Thanks man didn't have much time to mess with this.

**Comment by dorrance** [comment]
@jewbmx  @Tempest0580  currently there is no security involved with streams previously when i looked in the morning they were using cookies for streams.

**Comment by dorrance** [comment]
i am glad i am not alone on this i sent you both emails let me know if you two want to do a collab thanks :) 

@jewbmx @Tempest0580

**Comment by jewbmx** [comment]
Just updated that text file link to have a cleaner fix. Same setup just a bit more simple.  Only thing forgotten was removing import urlparse since it isnt used now.
Current version for it is now 1.6 too incase anyone follows changes by that
