### ISSUE TITLE
AcronaiTV

### ISSUE THREAD

**Issue by SoulTV** [Tempest0580/Temptv#2]
Love the addon so far! I noticed that AcronaiTV isn't working but not just on TempTV also in Scrubs v2. The website pulls up and plays fine through a browser just not in any kodi addon it seems

**Comment by jewbmx** [comment]
Working fine on my end stream wise, just tested with amc, sam. jack, and action. (One of each section. Lol)

**Comment by Tempest0580** [comment]
Working fine for me as well. In fact i watch the Live 24-7 alot.

**Comment by SoulTV** [comment]
Ok so this is really dumb and may or may not be helpful. For some reason I cant play from the info dialog but if you bring it up using context menu and select play, it plays fine. Im using AZ2 but I'd assume this isn't specific to AZ2

**Comment by SoulTV** [comment]
Oddly usTVgo and the (Testing) ones play using the info dialog
