### ISSUE TITLE
trying to embed your  repo maybe addon.

### ISSUE THREAD

**Issue by darknessally** [Tempest0580/Temptv#21]
time for the talk let me know when you are free.

**Comment by darknessally** [comment]
https://github.com/darknessally/firerises/blob/test/plugin.video.ccloudtv/default.py

**Comment by Tempest0580** [comment]
Was you able to get this to work?

**Comment by dorrance** [comment]
Will need your help

**Comment by Tempest0580** [comment]
Shoot me a email tempest0580@gmail.com
