### ISSUE TITLE
TempTV cCloudTV colab'

### ISSUE THREAD

**Issue by jabales** [Tempest0580/Temptv#23]
Just recently Bane announced that a collaboration with Tempest was underway, witch is great news! I was just wondering how the project was going. cCloud has been without its USTVGo sources for quite some time.

**Comment by RickFromTexas** [comment]
I'm sure a lot of cCloud fans are curious as well.

**Comment by Tempest0580** [comment]
Still working on it. Trying to get the coding all worked out. Just kinda going slow. Between work and I have 2 other projects I'm in the middle of.

**Comment by RickFromTexas** [comment]
Thanks for the update Tempest, it's appreciated.
________________________________
