### ISSUE TITLE
Streamlive down

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/Temptv#25]
Hey Tempest,
As of Feb. 11th, 2020...8:45pm EST, Stream live is down. None of the links will work. Thought I'd pass it along.

Thanks for your efforts, dude.

Have a good one.

**Comment by Tempest0580** [comment]
Thanks for letting me know. I'll look into it.

**Comment by bjgood** [comment]
Hey Tempest,
I've discovered what the problem is with Streamlive. In streamlive.py, at the def play function, change...
result = 'http:' + result
to
result = 'https:' + result

It works after that change.

Later...

**Comment by Tempest0580** [comment]
Thanks. I'll change it and push a update soon as I can. I'm working on recoding some of tempest and temptv to improve some of the live tv and 1 click movies.

**Comment by Tempest0580** [comment]
Pushed a Update to fix this. Thanks again

**Comment by bjgood** [comment]
Thanks for the update, Tempest.
