### ISSUE TITLE
Live TV in Tempest/Temptv keeps stopping, restarting, or just stopping

### ISSUE THREAD

**Issue by RickFromTexas** [Tempest0580/Temptv#26]
Described the problem here: 

https://www.reddit.com/r/Addons4Kodi/comments/f82jyg/problem_with_live_tv_in_tempest_temptv/

Happens on Android TV (Shield), Android, Windows 10, affects ustvgo, 123tvnow, streamlive.

Thanks Tempest!

**Comment by Tempest0580** [comment]
Thanks I'll check it out

**Comment by RickFromTexas** [comment]
Appreciate it! I realize you're just hosting ustvgo, etc. so there may not be much you can do if it's their issue, just wanted to let you know what was happening.
________________________________

**Comment by RickFromTexas** [comment]
Saw the update, installed it, been watching TNT for several hours now with no problems at all. Thank you sir, whatever you did seems to have worked quite well. I'll let you know if I see any other issues.
