### ISSUE TITLE
Foreign channels not working

### ISSUE THREAD

**Issue by fcanela** [Tempest0580/Temptv#28]
Hello!

We have been unable to reproduce foreign channels. After entering the corresponding section and clicking any country, a spinner appears and then disappears, staying in the same country selection screen.

Please feel free to ask me for any context information that I can provide. I will update this issue shortly with my Kodi & TempTV versions.

Thanks.

**Comment by fcanela** [comment]
After digging in the codebase, it seems like that section is being populated with data from the readme present at `https://github.com/iptv-org/iptv`, parsed with the following regular expression: `'<tr><td align="left">(.+?)</td><td .+? nowrap=""><code>(.+?)</code>'`.

I tried to check for changes in the lasts days in the document structure and it seems it has remained the same.

**Comment by Tempest0580** [comment]
Can you post your kodi log. I'm not having any issues on my end. I've check tempest and temptv and they both load and play fine. 
Thanks

**Comment by fcanela** [comment]
Thanks for the fast response. I will try to gather the logs.
