### ISSUE TITLE
USTVGo down again

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/Temptv#29]
Hi Tempest,
It looks like the ustvgo website has added an extra step to resolving a request by a user. It looks to be an easy fix.

Forgot to mention. The site is down.

Hope all is well with you and yours. Same to JewBMX. These are crazy times.

Later...

**Comment by Tempest0580** [comment]
Well they had added some extra security as well, I'll probably push a update soon.
Its not a perfect fix but until i can write a better one it will work. Might have to click it more than once to get it to play, but so far it work on average the second click.
Thanks

**Comment by Tempest0580** [comment]
Pushed a update, Its a crude fix for now. May have to click the channels more than once.
Working on a better fix.
Thanks

**Comment by meNick** [comment]
for version 2.0.60: ustvgo is not working for me on any channel. ditto for tempest as well.
fyi - I am using streamlive which is available in both tempest and temptv and all channels working.

**Comment by bjgood** [comment]
> for version 2.0.60: ustvgo is not working for me on any channel. ditto for tempest as well.
> fyi - I am using streamlive which is available in both tempest and temptv and all channels working.

Step down to 2.0.59. It works fine.

**Comment by Tempest0580** [comment]
Cool I'll roll it back shortly

**Comment by Tempest0580** [comment]
Pushed a update. Should come through shortly. 
Thanks

**Comment by meNick** [comment]
Good news! version-2.0.61 (just released) runs all channels in ustvgo and in streamlive. :)
Thanks ameigo! Both temptv and tempest are my #1 and #1 apps (can't figure which is #2)
