### ISSUE TITLE
Pause

### ISSUE THREAD

**Issue by SoulTV** [Tempest0580/Temptv#3]
Since I'm here already lol. It would be cool to be able to pause TempTV like TvTap. Might already be in the works, just throwing it out there.

This isn't an issue but I'm not sure where to mark it as a feature request

Thx again for the awesome addon!

**Comment by Tempest0580** [comment]
Ill look into it but not sure if i can set up a pause for the live Tv

**Comment by SoulTV** [comment]
All good. Just thought I'd ask
