### ISSUE TITLE
Arconai tv has stopped working

### ISSUE THREAD

**Issue by pitsi** [Tempest0580/Temptv#30]
As of today, arconai tv no longer works. Clicking on any link pops up a message saying "could not deobfuscate the code" on kodi itself and this bit on the log
`2020-04-14 18:11:12.286 T:140370564548736   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.arconaitv/?selection=stream.php%3Fid%3D48&mode=play]`

Thank you in advance.

**Comment by Tempest0580** [comment]
The Website code has changed, I'm working on a fix.
Thanks

**Comment by pitsi** [comment]
One thing I would like to admit. 
I found the site during the quarantine, ~2 weeks ago, and a couple of days later I found your addon. The first thing I noticed on the addon was the message on the top saying that the site needs help from donations. 
If the reason of changing the code is to fight the extra traffic that the addon produces without the revenue from the ads, I think it would be better to leave it unfixed, at least until the whole thing calms down.
Thank you.

**Comment by Tempest0580** [comment]
Next update I'm removing acronaitv until I figure out a fix or until I figure something else out. I'm trying to figure a way to do the 24/7 shows myself.

**Comment by pitsi** [comment]
Does this mean the addon will become unavailable completely? Shall we remove it first?

**Comment by Tempest0580** [comment]
The acronaitv addon its self will be but temptv will still work.

**Comment by Tempest0580** [comment]
Pushed a update. Added a new live tv source(Testing). Removed arconaitv until I can fix it or find a new source.
Thanks
