### ISSUE TITLE
How can I recommend another great website that plays free IPTV?

### ISSUE THREAD

**Issue by derrgoo** [Tempest0580/Temptv#31]

**Comment by Tempest0580** [comment]
If you have a site you want me to try and add just post here or email me the link.
Thanks

**Comment by derrgoo** [comment]
Hi, Thanks for the email. I came across a website that seems to be good streams and free along with non geo restricted it appears. The website is zynetv.net. Has several categories and would be a good back up for people.

Sorry to hear about 24/7.

**Comment by Tempest0580** [comment]
Thanks I'll take a look and see what I can do with that site.

**Comment by Tempest0580** [comment]
Next update should include channels for zynetv.net.
Thanks

**Comment by Tempest0580** [comment]
Pushed a update. Added your source. Thanks

**Comment by derrgoo** [comment]
Hi,

I am still seeing temptv 2.0.61. Which is the newest with the update? Thanks!

**Comment by Tempest0580** [comment]
2.0.62 is the latest. Sometimes it can take a bit to come through.

**Comment by derrgoo** [comment]
Is it in your repo. I am only seeing 61. https://tempest0580.github.io/

Kind Regards,

Derrick
________________________________

**Comment by derrgoo** [comment]
Ok! Reloaded and updated. Looks like a few are down on the Addon but www working.

Kind Regards,

Derrick
________________________________

**Comment by Tempest0580** [comment]
I through that together quick. I'm going to work on it more and see if I can make improvements on it.
Thanks

**Comment by derrgoo** [comment]
Thanks. Appreciate whenever you get the time!

Kind Regards,

Derrick
________________________________

**Comment by Tempest0580** [comment]
Unfortunately both sites are screwed at the moment.  Looks like both sites run off ustvgo. I'm working on another site now. Just have to get my code right.

**Comment by derrgoo** [comment]
Cool. At least ustvgo is up👌

Kind Regards,

Derrick
________________________________

**Comment by derrgoo** [comment]
Looks like ustvgo is switching links.

https://watchnewslive.tv/cnn1/.


Kind Regards,

Derrick
________________________________

**Comment by derrgoo** [comment]
Well done lmkmedia excellent streams.  Thank you. 👌

Kind Regards,

Derrick
________________________________
