### ISSUE TITLE
Resolveurl hoster

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/Temptv#36]
Hey Tempest,
This is about vidnode from resolveurl. If you include "load" in the pattern line...

pattern = '(?://|\.)(vidnode\.net)/(?:streaming|load)\.php\?id=([a-zA-Z0-9]+)'

and include it in the def get_url section...

return self._default_get_url(host, media_id, 'https://{host}/load.php?id={media_id}')

the blooming thing actual works once in awhile.

Check it out. Maybe you can submit it if you like.

**Comment by Tempest0580** [comment]
Just seen this, Ill see about submitting it to resolveurl, also every site that i have seen with the load in the pattern also has the same stream but it doesnt include the load in the pattern.
Thanks

**Comment by bjgood** [comment]
vidnode usage at websites seems to be ebbing quite a bit replaced by vidcloud9. The pattern line of vidcloud9 is very similar to the original vidnode (streaming.php). Just for laughs I've added load to its pattern line. Seems to work that way too.

Later, Tempest. :).
