### ISSUE TITLE
24/7 not working

### ISSUE THREAD

**Issue by gigiof4** [Tempest0580/Temptv#39]
all the sudden yesterday the TempTV 24/7 (arconaiTV) just stopped working with message ""The website has changed or we are downloading from wrong website"
any ideas on how to fix or is this an issue I have to wait till it's fixed on that end?

**Comment by JayDee696969** [comment]
> all the sudden yesterday the TempTV 24/7 (arconaiTV) just stopped working with message ""The website has changed or we are downloading from wrong website"
> any ideas on how to fix or is this an issue I have to wait till it's fixed on that end?

Probably because the website is down..https://www.arconaitv.us/

**Comment by YKL66** [comment]
@Tempest0580 - Here is a site you can scrape for 24/7 (reboot.tube) Just add the (https) didnt want to have live links on you page.

**Comment by SerpentDrago** [comment]
jesus that site is completely 100 percent unprotected. you can just figure out the url and play near anything you want ..

**Comment by darknessally** [comment]
@Tempest0580  don't add them i added them for a day  took less then 30 mins to scrape the entire site they have unstable server which couldn't even take 100 users The dev asked me to remove it since his server couldn't handle the traffic i reached out to them to so i can provide CDN solution

**Comment by Tempest0580** [comment]
> @Tempest0580 don't add them i added them for a day took less then 30 mins to scrape the entire site they have unstable server which couldn't even take 100 users The dev asked me to remove it since his server couldn't handle the traffic i reached out to them to so i can provide CDN solution

Well according to a reddit user I'm already scraping the site and you still are. I cant stand people that run their mouths without knowing shit. I haven't even had the time to even trying to scrape it.

**Comment by SerpentDrago** [comment]
I locked and commented on that reddit thread .  I have no idea what he guy was going on about . Obviously you were just trying to reach out to the site owner to warn him that traffic was going to go up even if you didn't scrape it . which your not yet . 

Also the site doesnt' even provide direct 24/7  streams it just random plays content from various shows hosted directly on the server . No way that site would survive a kodi addon .
