### ISSUE TITLE
"All" option

### ISSUE THREAD

**Issue by SoulTV** [Tempest0580/Temptv#4]
I've been trying to combine some of the sections to make an "All" section but for some reason I can only populate it with one section at a time (no coding experience).
I'm wondering if y'all can add an "all" section with (Entertainment, Movies, Kids, Sports, News and Testing) sections. It'd be nice to be able to scroll all the channels in one list.  

Thx!

**Comment by Tempest0580** [comment]
ill look into putting them all into one section. Everything in the Testing section im about to weed out the bad ones and move anyways.

**Comment by Tempest0580** [comment]
Pushed a update. I made a section with all the English channels in it. Let me know what you think

**Comment by SoulTV** [comment]
Just got a chance to check it out. It's working great! Thx man. Only thing that would be nice is if the list was sorted alphabetically. Also, which sections are a part of this? Is acronai, usatvgo, stream live and the entertainment, sports, etc' at the top apart of the "All English" section?

**Comment by Tempest0580** [comment]
Soon as I get a chance I'll get those put alphabetical also. And that's just entertainmen, sports, kids, etc. Those other are pulled separately so It wont be easy to add them to that list

**Comment by Tempest0580** [comment]
Your welcome.  And ya I still have lots to do with it. Mainly the 1 click movies and shows. They are just so time consuming.  Lol
