### ISSUE TITLE
New install: Some dependencies not found

### ISSUE THREAD

**Issue by ryester27** [Tempest0580/Temptv#40]
When trying to install TempTV on a fresh Kodi 18.7.1 installation, the following dependencies are not available when trying to install the video add-on:

- script.module.js2py
- script.module.pyjsparser
- script.module.cryptopy
- plugin.video.gdrive
- script.module.win_inet_pton

I don't remember before having to install another repository to get these dependencies. Using repository.temptv-0.0.5.zip

**Comment by Tempest0580** [comment]
I'll look into this. Thanks

**Comment by Tempest0580** [comment]
Sorry took so long. This issue should now be fixed. Thanks

**Comment by ryester27** [comment]
Hello. Just tried again, and temptv was able to install successfully now. However I'm still seeing some dependencies that aren't available:

script.module.cryptopy
plugin.video.gdrive
script.module.win_inet_pton

Is this something I still need to concern myself with, being an Arch Linux user?

**Comment by Tempest0580** [comment]
> Hello. Just tried again, and temptv was able to install successfully now. However I'm still seeing some dependencies that aren't available:
> 
> script.module.cryptopy
> plugin.video.gdrive
> script.module.win_inet_pton
> 
> Is this something I still need to concern myself with, being an Arch Linux user?

I dont think either of my addons require those dependencies. Not sure if its because of Arch linux either. I use linux mint myself. Thanks
