### ISSUE TITLE
myustv again

### ISSUE THREAD

**Issue by mattstvmedia** [Tempest0580/Temptv#42]
worked for an hour then stopped

**Comment by Tempest0580** [comment]
> worked for an hour then stopped

They site keeps changing. I'll work on different way to scrape the site that will fix the error when it tries to scrape the site. Thanks

**Comment by Tempest0580** [comment]
Pushed a update to fix this. Thanks

**Comment by mattstvmedia** [comment]
Awesome... Greatly appreciated
