### ISSUE TITLE
Foreign channels doesn't work anymore

### ISSUE THREAD

**Issue by simakuutio** [Tempest0580/Temptv#46]
Github page which was the primary source for those channels (https://github.com/iptv-org/iptv), have been taken down.

Until alternative source is found, that part of TempTV doesn't work :(

**Comment by Tempest0580** [comment]
So it looks like they are trying to dispute the case that the github was taken down. I added most of the foreign channels back for now. Let me know if its missing any that you need and I'll try to add them back soon as I can. Thanks
