### ISSUE TITLE
VPN locked

### ISSUE THREAD

**Issue by Z17922** [Tempest0580/Temptv#47]
Hello there. This was a great addon. Alas! I used nordvpn to access. However since version x.77 I can’t access. It gives me the message: VPN LOCKED. Can you fix it?
Thanks

**Comment by Tempest0580** [comment]
I pushed a fix, I don't us a vpn but I'll look into a vpn to see if i can fix that, As of now the other channels should be working again once it updates. Thanks

**Comment by Z17922** [comment]
Yes thank you. It is working again.
Best,
Z.
