### ISSUE TITLE
Korean Central Television doesn’t work

### ISSUE THREAD

**Issue by petersmith500** [Tempest0580/Temptv#48]
This channel does not play at all. When I select Korean Central Television from the South Korea folder what it will do is load but then it will cancel without playing before I get to the screen. All the other foreign channels work. Kcnawatch.org also works. Thanks.

**Comment by Tempest0580** [comment]
The foreign channels source has been shut down so those are the only ones I have as of now, they are working on trying to get back up and running. Hopefully they will, I am on the look out for a replacement if they are not able to though.  Thanks
