### ISSUE TITLE
Usa TV Go after update to 2.0.79 is not working 

### ISSUE THREAD

**Issue by Z17922** [Tempest0580/Temptv#49]
Hello friend.
In the previous roll out ( release 2.0.78 ) everything seemed to work perfectly. But now  in 2.0.79, only few stations (on Ustreamix mainly) are working. Foreign channels are not  adversely affected.

When clicking on a link on USA TV Go, let us say, CNN, a process is started and instead of showing eventually a cnn.m3u8 link, it simply drops. Same for other channels.

Thank you for your help.
Best,
Z.

**Comment by Tempest0580** [comment]
I'll be pushing a update today. Thanks

**Comment by Z17922** [comment]
It is working again! Thank you.
Z.
