### ISSUE TITLE
Streamlive additions

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/Temptv#5]
Hey Tempest,
In the Streamlive section I have a few additions I came up with. Unlike other people I like SD quality links. Sometimes HD (720) causes my streaming of a channel to freeze. The MSNBC link is 720, though.

Here they are...

('CNN SD', 'view/68967/CNN-(SD)', 'https://cdn.cnn.com/cnn/.e1mo/img/4.0/logos/CNN_logo_400x400.png'),

('MSNBC', 'view/77067/MSNBC', 'https://github.com/jewbmx/resource.images.studios.white/blob/master/resources/MSNBC.png?raw=true'),

('NBC SD', 'view/69116/NBC-(SD)', 'https://github.com/jewbmx/resource.images.studios.white/blob/master/resources/NBC.png?raw=true'),

I'll look and see if I can find some more.

Later...

**Comment by SoulTV** [comment]
streamlive is working great for me even in HD

**Comment by bjgood** [comment]
> Is streamlive working good for you?

Yeah, it works for me. It's real slow opening, though, but, that's OK.

Streamlive is a hard one to keep going. I had it going a few months back, but they changed something, and after a while I gave up. 

Hats off to you and Jewbmx for a nice addon.

Also, just because someone is "borrowing" your scrapers is no reason to quit fixing or creating them. We common folk need your work.

Thanks, Tempest.

Later...

**Comment by bjgood** [comment]
Hey Tempest,
Two small errors in 2.0.12. One is CNN SD...you have CNN HD on the CNN SD line. The second...TBS SD line the icon link has hhttp instead of http.

**Comment by Tempest0580** [comment]
Ok I'll try to fix those today. It was late when I added those in. Lol

And it's not really that other people use my scrapers. It more of the fact that they take them and remove credit and claim them. 

I do this for me. But I dont mind adding stuff or making things more convenient for other people.

**Comment by Tempest0580** [comment]
Pushed a update to fix those issues. Added a few more SD channels

**Comment by bjgood** [comment]
Got the new release. Thanks.

**Comment by bjgood** [comment]
Get job on this addon, Tempest. The hard work put into it is very much appreciated. :).

Later...
