### ISSUE TITLE
Request: ustvgo cc

### ISSUE THREAD

**Issue by simakuutio** [Tempest0580/Temptv#50]
ustvgo stream contains now cc (subtitles). Question is, does Kodi have functionality on it's API to handle rtmp which have cc embedded. I tried to read kodi documentation about possible features but didn't find it easily. It's possible Kodi doesn't even support such thing (yet) but ... worth of evaluation anyway if someone finds a way ...

**Comment by Tempest0580** [comment]
> ustvgo stream contains now cc (subtitles). Question is, does Kodi have functionality on it's API to handle rtmp which have cc embedded. I tried to read kodi documentation about possible features but didn't find it easily. It's possible Kodi doesn't even support such thing (yet) but ... worth of evaluation anyway if someone finds a way ...

I'd have to look into it. Thanks
