### ISSUE TITLE
USTV Go not working

### ISSUE THREAD

**Issue by arudisu** [Tempest0580/Temptv#54]
VPN locked or code changed error.

**Comment by arudisu** [comment]
Must have been something with my VPN. It wouldn't work connecting to US (using PIA) but connected to Canada and it works.

**Comment by simakuutio** [comment]
Yes, all channels (!) are now VPN (NordVPN atleast) blocked. Not sure how they do detect when NordVPN is being used. Other VPN's doesn't seem to do the trick (ok, there were one but generally other than NordVPN doesn't work). Not even native US ip works...

**Comment by arudisu** [comment]
Thanks for the info.  Has been fine up until this morning.  But I got it to work with my same VPN by connecting through Canada instead of the US
