### ISSUE TITLE
Temptv wont open anything in kodi

### ISSUE THREAD

**Issue by gazoo1422** [Tempest0580/Temptv#55]
Temptv wont open anything in kodi

**Comment by simakuutio** [comment]
Because they forced everything behind VPN, check other tickets here for futher discussion about this issue.

**Comment by gazoo1422** [comment]
I picked another state within the VPN and it's working fine now...Thank You
for replying

**Comment by arudisu** [comment]
This is happening to me as well.  I even changed my VPN to nordvpn and it still says VPN locked

**Comment by Tempest0580** [comment]
Pushed a update to fix UstvGo, Code Changed. Thanks

**Comment by gazoo1422** [comment]
This is true and it did happen to me, it was working for the few hours I
watched tv and the next time I turned it back on I got that message again
so TempTv is not even trying or showing up as an option to open anything,
the channel is going to another source...I love TempTv so hopefully it will
work its self out soon
