### ISSUE TITLE
Foreign Channels (UK)

### ISSUE THREAD

**Issue by snoopymail** [Tempest0580/Temptv#7]
Great addon and I've been using it for a while now... When you get the chance, please can you have a look at the UK Foreign channels, as they've been down for a few days?

**Comment by jewbmx** [comment]
Just did a quick check to help out this issue and the channels i tried failed too, when tossed in the browser ya get a forbidden error so they need a update forsure or swapped out lol

**Comment by jewbmx** [comment]
If ya need a replacement while they are down this one is made for other countries if i recall  https://github.com/jewbmx/repo/blob/master/zips/script.module.livenettv.net/script.module.livenettv.net-1.2.1.zip

Havent tried it for a while but the tvtap version of it still works fine so its probably still good lol

**Comment by Tempest0580** [comment]
Updated UK channels. Will Update and ad more as i can. Thanks
