### ISSUE TITLE
Streamlive question

### ISSUE THREAD

**Issue by bjgood** [Tempest0580/Temptv#9]
Hi Tempest,
Are streamlive links working for you? As of two days ago they stopped working for me. In the Kodi log I'm getting a 404 for the links I try to watch, but on the website they work.

Just wondering.

Later...

**Comment by Tempest0580** [comment]
I don't use it much myself but I'll take a look at it

**Comment by Tempest0580** [comment]
I removed Streamlive until i can fix it.
